// noauth/frontend-react/src/Customer.js
import { useState, useMemo, useContext } from 'react';
import axios from 'axios';

import { Table } from 'reactstrap';

const CustomerTable = ({ items, loading }) => {
    if (loading) {
	return <h2>Loading...</h2>;
    }
    return(
	<Table bordered hover striped responsive>
	    <thead>
		<tr>
		    <th>id</th>
		    <th>name</th>
		    <th>email</th>
		</tr>
	    </thead>
	    <tbody>
		{items.map(cs =>
		    <tr key={cs.id}>
			<td>{cs.id}</td>
			<td>{cs.name}</td>
			<td>{cs.email}</td>
		    </tr>
		)}
	    </tbody>
	</Table>
    );
}

const CustomerList = () => {
    
    const [items, setItems] = useState([]);
    const [loading, setLoading] = useState(false);

    useMemo(() => {
	const fetchItems = () => {
	    setLoading(true);

	    axios.get(`${process.env.REACT_APP_API_SERVER}/api/customer/`)
		.then(res => {
		    setItems(res.data.results);
		    setLoading(false);
		})
		.catch(error => {
		    console.log(error);
		})
	};

	fetchItems();
    }, []);

    return (
	<div >
	    <h1 className='text-primary'>Customer List</h1>
	    <CustomerTable items={items} loading={loading} />
	</div>
    );
};

export default CustomerList;

// noauth/svelte/src/cpnts/Customer.svelte
<script>
    import { onMount } from "svelte";
    import axios from "axios";

    let users = [];
    
    console.log(import.meta.env.VITE_APP_API_SERVER)

    onMount(async () => {
    const res = await axios.get(`${import.meta.env.VITE_APP_API_SERVER}/api/customer/`);
    users = res.data.results;
    console.log("axios:", users);
    });

</script>


<h2>This is Customer.</h2>

{#await users}
<p>Loading ...</p>
{:then users}
<div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
        <thead class="table-light">
            <tr>
                <th>id</th>
                <th>name</th>
                <th>email</th>
            </tr>
            </thead>
            <tbody>
                {#each users as cs}
                <tr>
                    <td>{cs.id}</td>
                    <td>{cs.name}</td>
                    <td>{cs.email}</td>
                </tr>
                {/each}
            </tbody>
    </table>
</div>
{/await}
