// google-oauth/frontend-svelte/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";
  import Top from "./components/Top.svelte";
  import Customer from "./components/Customer.svelte";
  import NoMatch from "./components/NoMatch.svelte";
  import LoginPage from "./components/LoginPage.svelte";

  export let url = "";
</script>

<div class="container-sm">
  <Router {url}>
    <nav>
      <table class="table-borderless table-responsive">
        <tbody>
          <tr><td><Link to="/">Top</Link></td></tr>
          <tr><td><Link to="/customer">Customer</Link></td></tr>
        </tbody>
      </table>
    </nav>

    <div>
      <Route path="/"><Top /></Route>
      <Route path="/customer"><Customer /></Route>
      <Route path="/login"><LoginPage /></Route>
      <Route path="*"><NoMatch /></Route>
    </div>
  </Router>
</div>

<style>
</style>

// noauth/frontend-react/src/App.js
import { Routes, Route, Link } from 'react-router-dom';
import Customer from './Customer';
import { Table, Container } from 'reactstrap';

const NoMatch = () => {
    return <h2>Page does not exist.</h2>;
}

const Top = () => {
    return <h2>This is top page.</h2>;
}

const App = () => {
  return (
      <div>
	  <Container fluid="sm">
	      <Table borderless responsive size="sm">
		  <tbody>
		      <tr><td><Link to={`/`}>Top</Link></td></tr>
		      <tr><td><Link to={`/customer`}>Customer</Link></td></tr>
		  </tbody>
	      </Table>
	      
	      <Routes>
		  <Route index element={ <Top /> } />
		  <Route path="/customer" element={ <Customer /> } />
		  <Route path="*" element={<NoMatch />} />
	      </Routes>
	  </Container>
      </div>
  );
}

export default App;
