// noauth/frontend-react/src/Customer.js
import { useState, useMemo, useContext } from 'react';
import axios from 'axios';

import { Table } from 'reactstrap';

const CustomerTable = ({ items, loading }) => {
    if (loading) {
	return <h2>Loading...</h2>;
    }
    return(
	<Table bordered hover striped responsive>
	    <thead>
		<tr>
		    <th>id</th>
		    <th>name</th>
		    <th>email</th>
		</tr>
	    </thead>
	    <tbody>
		{items.map(cs =>
		    <tr key={cs.id}>
			<td>{cs.id}</td>
			<td>{cs.name}</td>
			<td>{cs.email}</td>
		    </tr>
		)}
	    </tbody>
	</Table>
    );
}

const CustomerList = () => {
    
	const [items, setItems] = useState([]);
	const [loading, setLoading] = useState(false);

	useMemo(() => {
		const fetchItems = async () => {
			setLoading(true);
			try {
				let res = await axios.get(`${process.env.REACT_APP_API_SERVER}/api/customer/`)
				setItems(res.data.results);
			} catch (error) {
				console.log(error);
			} finally {
				setLoading(false);
			}
		};
		fetchItems();
	}, []);

    return (
	<div >
	    <h1 className='text-primary'>Customer List</h1>
	    <CustomerTable items={items} loading={loading} />
	</div>
    );
};

export default CustomerList;

// google-oauth/frontend-svelte/src/components/Customer.svelte
<script>
  import { onMount } from "svelte";
  import { apiAxios } from "../lib/apiAxios";
  import LogoutButton from "./LogoutButton.svelte";

  let customers = [];
  let Loading = true;

  onMount(async () => {
    try {
        await new Promise(r => setTimeout(r, 1000))

        let res = await apiAxios.get(`/api/customer/`);
        customers = res.data.results;
        console.log("axios:", customers[0]);
    } catch(error){
        console.log("axios error:", error);
    } finally {
      Loading = false;
    }
  });

</script>

<LogoutButton />
<h2>This is Customer.</h2>

{#if Loading}
  <p>Loading ...</p>
{:else}
  <div class="table-responsive">
    <table class="table table-bordered table-hover table-striped">
      <thead class="table-light">
        <tr>
          <th>id</th>
          <th>name</th>
          <th>email</th>
        </tr>
      </thead>
      <tbody>
        {#each customers as cs}
          <tr>
            <td>{cs.id}</td>
            <td>{cs.name}</td>
            <td>{cs.email}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
{/if}
